### ISSUE TITLE
Define workflows for Signals Work Orders

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/react-knack#12]
@dianamartin @johnclary, could y'all let me know which of the activities on the Y-axis we expect technicians to do in the field?

### Technician Permitted Activities by Work Order Status
 
<img width="1010" alt="screen shot 2018-09-19 at 4 33 17 pm" src="https://user-images.githubusercontent.com/5697474/45782928-f41ca880-bc29-11e8-9162-cb457d184d1d.png">

**Comment by johnclary** [comment]
@mateoclarke have you seen this?
https://github.com/cityofaustin/data-tracker-guides/tree/master/signs_markings

**Comment by mateoclarke** [comment]
Does all of the above hold true for Signals Work Orders? Now that we are changing the focus of this MVP? @johnclary

**Comment by johnclary** [comment]
@mateoclarke not exactly, we need to make you a new one.

**Comment by mateoclarke** [comment]
ok, I've updated the title of this issue so its more actionable.

**Comment by mateoclarke** [comment]
@dianamartin and @johnclary are meeting with AMD to define what technicians should be able to do out in the field on tablets this Friday and will report back.

**Comment by mateoclarke** [comment]
This meeting happened during sprint #3, @dianamartin has notes and has begun implementing a more streamlined workflow.
