### ISSUE TITLE
Login Screen for Authentication with Knack

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/react-knack#13]
A user needs an active user token from Knack to be able to request Views from the Knack API.

There needs to be a login page so this token is set and retrievable for our API queries.  

Docs: https://www.knack.com/developer-documentation/#users-sessions-amp-remote-logins

**Comment by johnclary** [comment]
so it looks like there's a method for remote logins? nice.

**Comment by mateoclarke** [comment]
This task is complete a while back with https://github.com/cityofaustin/react-knack/pull/17
