### ISSUE TITLE
Attachment preview from Work Order Detail page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/react-knack#21]
Right now, the attachment field data is being dumped as raw HTML. It looks like a link, but doesn't link anywhere. It seems to make a call to the knack API in its href. How do we get the true S3 file location from knack and present it on a mobile device?

**Comment by johnclary** [comment]
@mateoclarke attachment link seems to be working for me. i was able to click on an attachment and view it.

https://deploy-preview-20--react-knack.netlify.com/markings/5bafaacc6211e609f09ee976

**Comment by mateoclarke** [comment]
great! I'll close this out and we can reopen if its an issue. Thanks for double checking me @johnclary
