### ISSUE TITLE
CSS grid not working on Andriod Chrome

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/react-knack#39]
Device: Verizon Ellipsis 8
OS: Andriod 5.1.1
Chrome version: 46

I'm checking to see if an update of the Chrome app on this device would fix this styling issue but it seems to be stuck on "Download pending" 🤷‍♂️ 

![screenshot_2018-10-08-13-49-05 1](https://user-images.githubusercontent.com/5697474/46628743-3daf3380-cb04-11e8-91b9-5a3b506d3064.png)

**Comment by dontehightower** [comment]
:sweat_smile: I'll write some layout rules for browsers that don't support Grid.
