### ISSUE TITLE
Document Signal Work Order User Rules/Permissions

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/react-knack#45]
Document what actions a user can take based on role and work order status.

@dianamartin @mateoclarke Here's the documentation: https://docs.google.com/spreadsheets/d/1kyqQnyC3gqMo3X0EeqUumRO0RZx0PRaEDfmeC1WGC5E/edit?usp=sharing

**Comment by mateoclarke** [comment]
Added that here: https://github.com/cityofaustin/react-knack/commit/4463b939efc1c4acbf620aa57f5b54a440bf24f0#diff-04c6e90faac2675aa89e2176d2eec7d8
