### ISSUE TITLE
History/Audit Log of Work Order Reassignments

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/react-knack#79]
_@johnclary  Need clarification on whether this is a feature request for the mobile app or for desktop._

The idea here is to make it more visible if work orders are getting reassigned over the course of their history. An edge case was mentioned that a user could reassign work to somebody as a mistake or a joke. We want to discourage this.

**Comment by johnclary** [comment]
We can implement this with form submission roles on the Knack side. The log would be available in the desktop app but no need to implement in Knack mobile.

@dianamartin let's add this to the AMD backlog and prioritize from there. The issue can be closed here IMO.
